services:
  app:
    build: .
    container_name: moviemania
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
